name: ci

on:
  push:
    paths-ignore:
      - 'chart/Chart.yaml'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "Get version from package.json"
        id: version
        run: |
          echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run CI
        run: npm run lint
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2
      - name: Lint chart
        run: |
          helm lint chart
      - name: Build Image
        run: |
          docker build . --tag bashofmann/nodejs-demo-app:${{steps.version.outputs.version}}
      - name: Scan Image
        uses: neuvector/scan-action@main
        with:
          image-repository: bashofmann/nodejs-demo-app
          image-tag: ${{steps.version.outputs.version}}
          min-high-cves-to-fail: '1'
          min-medium-cves-to-fail: '1'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: |
          docker push . --tag bashofmann/nodejs-demo-app:${{steps.version.outputs.version}}
      - name: Bump helm chart
        run: |
          sed -i 's/^appVersion: .*/appVersion: ${{steps.version.outputs.version}}/' chart/Chart.yaml
          git config --global user.name 'GithubAction'
          git config --global user.email 'bashofmann@users.noreply.github.com'
          git add chart/Chart.yaml
          git commit -m "Bump helm chart"
          git push


