name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run CI
        run: npm run lint
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2
      - name: Lint chart
        run: |
          helm lint chart
      - name: Build Image
        run: |
          docker build . --tag bashofmann/nodejs-demo-app:latest
      - name: Scan Image
        uses: neuvector/scan-action@main
        with:
          image-repository: bashofmann/nodejs-demo-app
          image-tag: latest
          min-high-cves-to-fail: '1'
          min-medium-cves-to-fail: '1'
